"""initial migration

Revision ID: 74331a13626b
Revises:
Create Date: 2025-11-20 08:14:31.340480

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "74331a13626b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
