"""

Revision ID: a487a0269c6d
Revises: 74331a13626b
Create Date: 2025-11-20 08:42:44.252149

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a487a0269c6d"
down_revision: str | Sequence[str] | None = "74331a13626b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
