"""add tags and post_tags table

Revision ID: afac8ee83228
Revises: 9e6dd15ac637
Create Date: 2025-11-20 09:54:43.454849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afac8ee83228"
down_revision: str | Sequence[str] | None = "9e6dd15ac637"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("entity_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "post_tags",
        sa.Column("post_id", sa.UUID(), nullable=True),
        sa.Column("tag_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.entity_id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
